// Inside the Rig (lab 011) — the content catalogue. Every id in ids.ts gets a
// PartContent entry (name, system, tags, tooltip, and — for Level A products —
// the deeper modal sections). The 17 scroll chapters and the hero/credits
// copy live here too, so the whole experience's words are one file.
//
// No brands, on purpose: parts are named for what they are ("the graphics
// card", "a 360 mm liquid cooler"), specs are given as generic classes, and
// tools/brand-scrub.mjs fails CI if a manufacturer or product name gets in.

import type { Chapter, CopyBlock, PartContent, SystemId } from "./types";
import type { PartId } from "./ids";

/** Slice-3 Level B helpers: the same shape for every fan's rotor. */
const rotorOf = (id: PartId, fanLabel: string, fanId: PartId, system: SystemId, whatFor: string): PartContent => ({
  id,
  name: `${fanLabel} rotor`,
  system,
  level: "B",
  tags: ["rotor", "blades", "impeller", "fan blades", "hub", fanLabel.toLowerCase()],
  short: `The spinning hub and blade set of the ${fanLabel.toLowerCase()}, ${whatFor}.`,
  whatItDoes: "Nine swept blades on a bearing-mounted hub. Blade shape and pitch set how much air moves per turn against the resistance of fins, filters and mesh, and how much of that work becomes noise.",
  related: [fanId],
});

export const PARTS = {
  // ── chassis ───────────────────────────────────────────────────────────
  "case-frame": {
    id: "case-frame",
    name: "Case Frame",
    productName: "Full-tower case",
    system: "chassis",
    level: "A",
    tags: ["case", "chassis", "tower", "pc case", "full tower", "e-atx case", "enclosure"],
    short: "The full-tower frame that holds every system in the machine and shapes its airflow.",
    whatItDoes: "Holds the motherboard, GPU, PSU and cooling in a fixed layout and channels air from the front intake to the rear and top exhaust.",
    whyItMatters: "A large, well-vented case gives a big GPU and a 360mm radiator room to breathe, which keeps the whole system running cooler under load.",
    buying: "Clearance for your GPU and radiators, motherboard size support, the front-to-back airflow path, and cable-routing space behind the tray.",
    thisBuild: [
      "Full-tower case",
      "E-ATX / ATX support",
      "Tempered-glass sides",
      "Room for a GPU well over 400mm long",
      "Roughly 27 × 64 × 66 cm",
    ],
    specs: [
      { label: "Motherboard support", value: "E-ATX / ATX" },
      { label: "Radiator support", value: "360mm and up, top and front" },
      { label: "Front fans", value: "3 × 140mm" },
      { label: "Rear fan", value: "1 × 140mm" },
      { label: "Size class", value: "Full tower" },
    ],
    brand: {
      eyebrow: "THE CASE",
      title: "A full-tower case",
      body: "A large E-ATX tower with tempered-glass sides and room for a long GPU and 360mm radiators front and top.",
    },
    related: ["glass-left", "panel-right", "motherboard"],
  },
  "glass-left": {
    id: "glass-left",
    name: "Left Tempered Glass",
    system: "chassis",
    level: "A",
    tags: ["glass", "tempered glass", "side panel", "window", "left panel"],
    short: "Tempered-glass side panel that shows the internals and seals that side of the case.",
    whatItDoes: "Lets the build be seen while closing off that side of the case from dust and airflow loss.",
    related: ["case-frame", "panel-right"],
  },
  "panel-right": {
    id: "panel-right",
    name: "Right Side Panel",
    system: "chassis",
    level: "A",
    tags: ["side panel", "right panel", "steel panel", "case panel"],
    short: "Solid steel panel that closes the cable-management side of the case.",
    whatItDoes: "Encloses the rear of the motherboard tray and hides the bulk of the cable routing from view.",
    related: ["case-frame", "glass-left"],
  },
  "panel-front": {
    id: "panel-front",
    name: "Front Panel",
    system: "chassis",
    level: "B",
    tags: ["front panel", "front assembly", "front mesh", "intake panel"],
    short: "Front assembly and mesh that shapes how air is drawn into the case.",
    whatItDoes: "Shapes the case's intake path so the front fans can pull air in without excess restriction.",
  },
  "panel-top": {
    id: "panel-top",
    name: "Top Panel",
    system: "chassis",
    level: "B",
    tags: ["top panel", "top cover", "top vent"],
    short: "Top cover and vent over the case's top-mounted radiator and fan positions.",
    whatItDoes: "Lets warm air exhaust upward from a top-mounted radiator or fans while covering the bay.",
  },
  "psu-shroud": {
    id: "psu-shroud",
    name: "PSU Shroud",
    system: "chassis",
    level: "B",
    tags: ["psu shroud", "psu cover", "cable cover", "psu shield"],
    short: "Cover that hides the PSU and its bulk cabling beneath the motherboard tray.",
    whatItDoes: "Separates the PSU and its cabling from the main chamber for a cleaner look and less airflow interference.",
  },
  "front-io": {
    id: "front-io",
    name: "Front I/O Assembly",
    system: "chassis",
    level: "B",
    tags: ["front io", "front panel io", "power button", "usb ports", "audio jack", "io panel"],
    short: "Front-panel assembly holding the power button, USB ports and audio jack.",
    whatItDoes: "Gives easy front access to power, USB and audio without opening the case.",
  },
  "case-feet": {
    id: "case-feet",
    name: "Case Feet",
    system: "chassis",
    level: "B",
    tags: ["feet", "case feet", "stand", "riser"],
    short: "Raised feet that lift the case off the floor for underside intake clearance.",
    whatItDoes: "Raise the case enough for any bottom-mounted intake or PSU vent to draw air freely.",
  },

  // ── case cooling ──────────────────────────────────────────────────────
  "fan-front-1": {
    id: "fan-front-1",
    name: "Front Fan 1",
    productName: "140 mm case fan",
    system: "cooling",
    level: "A",
    tags: ["fan", "case fan", "front fan", "140mm fan", "140 mm", "intake fan", "stock fan"],
    short: "One of three 140mm fans pulling cool air into the front of the case.",
    whatItDoes: "Pulls cool air into the case across the GPU and motherboard.",
    whyItMatters: "Continuous front intake keeps the GPU, CPU cooler and power-delivery components from building up excess heat.",
    buying: "Airflow versus noise, static pressure if mounted behind a filter, and fan-header or ARGB compatibility with your motherboard.",
    thisBuild: ["140mm case fan", "Ships with the case", "Front intake position"],
    specs: [
      { label: "Size", value: "140mm" },
      { label: "Position", value: "Front intake" },
      { label: "Included with", value: "The case" },
    ],
    brand: {
      eyebrow: "FRONT INTAKE",
      title: "140mm intake fan",
      body: "One of three 140mm fans that start the case's front-to-back airflow path.",
    },
    related: ["fan-front-2", "fan-front-3", "fan-rear"],
  },
  "fan-front-2": {
    id: "fan-front-2",
    name: "Front Fan 2",
    productName: "140 mm case fan",
    system: "cooling",
    level: "A",
    tags: ["fan", "case fan", "front fan", "140mm fan", "140 mm", "intake fan", "stock fan"],
    short: "Second of three 140mm fans pulling cool air into the front of the case.",
    whatItDoes: "Pulls cool air into the case across the GPU and motherboard.",
    whyItMatters: "Continuous front intake keeps the GPU, CPU cooler and power-delivery components from building up excess heat.",
    buying: "Airflow versus noise, static pressure if mounted behind a filter, and fan-header or ARGB compatibility with your motherboard.",
    thisBuild: ["140mm case fan", "Ships with the case", "Front intake position"],
    specs: [
      { label: "Size", value: "140mm" },
      { label: "Position", value: "Front intake" },
      { label: "Included with", value: "The case" },
    ],
    brand: {
      eyebrow: "FRONT INTAKE",
      title: "140mm intake fan",
      body: "One of three 140mm fans that start the case's front-to-back airflow path.",
    },
    related: ["fan-front-1", "fan-front-3", "fan-rear"],
  },
  "fan-front-3": {
    id: "fan-front-3",
    name: "Front Fan 3",
    productName: "140 mm case fan",
    system: "cooling",
    level: "A",
    tags: ["fan", "case fan", "front fan", "140mm fan", "140 mm", "intake fan", "stock fan"],
    short: "Third of three 140mm fans pulling cool air into the front of the case.",
    whatItDoes: "Pulls cool air into the case across the GPU and motherboard.",
    whyItMatters: "Continuous front intake keeps the GPU, CPU cooler and power-delivery components from building up excess heat.",
    buying: "Airflow versus noise, static pressure if mounted behind a filter, and fan-header or ARGB compatibility with your motherboard.",
    thisBuild: ["140mm case fan", "Ships with the case", "Front intake position"],
    specs: [
      { label: "Size", value: "140mm" },
      { label: "Position", value: "Front intake" },
      { label: "Included with", value: "The case" },
    ],
    brand: {
      eyebrow: "FRONT INTAKE",
      title: "140mm intake fan",
      body: "One of three 140mm fans that start the case's front-to-back airflow path.",
    },
    related: ["fan-front-1", "fan-front-2", "fan-rear"],
  },
  "fan-rear": {
    id: "fan-rear",
    name: "Rear Fan",
    productName: "140 mm case fan",
    system: "cooling",
    level: "A",
    tags: ["fan", "case fan", "rear fan", "140mm fan", "140 mm", "exhaust fan", "stock fan"],
    short: "140mm fan that exhausts warm air from the rear of the case.",
    whatItDoes: "Pushes warm air out of the case, completing the front-to-back airflow path.",
    whyItMatters: "Exhaust airflow gives the air the front fans pull in somewhere to go, keeping the whole loop moving.",
    buying: "Airflow versus noise, static pressure if mounted behind a filter, and fan-header or ARGB compatibility with your motherboard.",
    thisBuild: ["140mm case fan", "Ships with the case", "Rear exhaust position"],
    specs: [
      { label: "Size", value: "140mm" },
      { label: "Position", value: "Rear exhaust" },
      { label: "Included with", value: "The case" },
    ],
    brand: {
      eyebrow: "REAR EXHAUST",
      title: "140mm exhaust fan",
      body: "The fan that closes the case's front-to-back airflow path by pushing warm air out of the rear.",
    },
    related: ["fan-front-1", "fan-front-2", "fan-front-3"],
  },

  // ── motherboard ───────────────────────────────────────────────────────
  motherboard: {
    id: "motherboard",
    name: "Motherboard",
    productName: "E-ATX desktop motherboard",
    system: "connectivity",
    level: "A",
    tags: ["motherboard", "mobo", "mainboard", "board", "e-atx", "logic board"],
    short: "The physical network that connects the PC's core systems to each other.",
    whatItDoes: "Provides the sockets, data lanes, power connections and controllers that let the CPU, GPU, memory, storage and peripherals operate as one system.",
    whyItMatters: "A high-end board gives the CPU and GPU full PCIe 5.0 bandwidth and power delivery strong enough that it never becomes the bottleneck.",
    buying: "Socket and chipset compatibility with your CPU, enough M.2 and PCIe lanes for your storage and GPU, memory support for the speed you want, and VRM quality if you plan to push the CPU hard.",
    thisBuild: [
      "E-ATX board, 305 × 277 mm",
      "High-end desktop chipset",
      "Four DDR5 DIMM slots",
      "Two PCIe 5.0 x16 slots, five M.2 slots",
      "USB4 and multi-gigabit networking",
    ],
    specs: [
      { label: "Form factor", value: "E-ATX" },
      { label: "Memory slots", value: "4 × DDR5" },
      { label: "PCIe slots", value: "2 × PCIe 5.0 x16" },
      { label: "M.2 slots", value: "5" },
      { label: "USB", value: "USB4" },
    ],
    brand: {
      eyebrow: "THE PLATFORM",
      title: "An E-ATX motherboard",
      body: "PCIe 5.0, four DDR5 slots, five M.2 positions and USB4 on a high-end desktop platform.",
    },
    related: ["cpu", "gpu", "dimm-a", "ssd"],
  },
  "vrm-heatsink-top": {
    id: "vrm-heatsink-top",
    name: "VRM Heatsink (Top)",
    system: "connectivity",
    level: "B",
    tags: ["vrm", "vrm heatsink", "power delivery", "voltage regulator", "mosfet heatsink"],
    short: "Heatsink cooling the VRM phases above the CPU socket area.",
    whatItDoes: "Draws heat away from the VRM's power-delivery components so they can keep supplying the CPU with stable power under load.",
  },
  "vrm-heatsink-side": {
    id: "vrm-heatsink-side",
    name: "VRM Heatsink (Side)",
    system: "connectivity",
    level: "B",
    tags: ["vrm", "vrm heatsink", "power delivery", "voltage regulator", "mosfet heatsink"],
    short: "Heatsink cooling the VRM phases along the side of the CPU socket.",
    whatItDoes: "Helps dissipate heat from the voltage-regulation circuitry feeding the CPU.",
  },
  "io-shroud": {
    id: "io-shroud",
    name: "I/O Shroud",
    system: "connectivity",
    level: "B",
    tags: ["io shroud", "io cover", "rear io shroud", "backplate cover"],
    short: "Decorative shroud covering the rear I/O block and upper motherboard edge.",
  },
  "chipset-heatsink": {
    id: "chipset-heatsink",
    name: "Chipset Heatsink",
    system: "connectivity",
    level: "B",
    tags: ["chipset", "chipset heatsink", "southbridge", "pch"],
    short: "Heatsink covering the board's chipset controller.",
    whatItDoes: "Cools the chipset that manages many of the board's high-speed lanes and controllers.",
  },
  "m2-heatsink": {
    id: "m2-heatsink",
    name: "M.2 Heatsink",
    system: "connectivity",
    level: "B",
    tags: ["m.2 heatsink", "ssd heatsink", "nvme heatsink", "m2 cover"],
    short: "Heatsink and cover that cools an M.2 SSD mounted on the motherboard.",
    whatItDoes: "Draws heat away from the SSD's controller and NAND so sustained transfers don't throttle.",
  },
  "pcie-slot-1": {
    id: "pcie-slot-1",
    name: "PCIe Slot 1",
    system: "connectivity",
    level: "B",
    tags: ["pcie", "pcie slot", "pci express", "x16 slot", "gpu slot", "pcie 5.0"],
    short: "Primary PCIe 5.0 x16 slot that the graphics card plugs into.",
    whatItDoes: "Carries data between the motherboard and GPU at full PCIe 5.0 bandwidth.",
  },
  "pcie-slot-2": {
    id: "pcie-slot-2",
    name: "PCIe Slot 2",
    system: "connectivity",
    level: "B",
    tags: ["pcie", "pcie slot", "pci express", "x16 slot", "second pcie slot"],
    short: "Second physical PCIe 5.0 x16 slot for additional expansion cards.",
  },
  "dimm-slots": {
    id: "dimm-slots",
    name: "DIMM Slots",
    system: "connectivity",
    level: "B",
    tags: ["dimm slots", "ram slots", "memory slots", "ddr5 slots"],
    short: "Four DDR5 slots that the memory kit's DIMMs install into.",
  },
  "atx-24pin-socket": {
    id: "atx-24pin-socket",
    name: "24-Pin Power Socket",
    system: "connectivity",
    level: "B",
    tags: ["24-pin", "atx power socket", "motherboard power connector"],
    short: "Main power socket where the PSU's 24-pin cable connects to the board.",
  },
  "eps-sockets": {
    id: "eps-sockets",
    name: "EPS Power Sockets",
    system: "connectivity",
    level: "B",
    tags: ["eps", "eps socket", "cpu power socket", "8-pin socket"],
    short: "Sockets near the CPU socket where the EPS power cables connect.",
  },
  "rear-io": {
    id: "rear-io",
    name: "Rear I/O Block",
    system: "connectivity",
    level: "B",
    tags: ["rear io", "io panel", "usb ports", "ethernet", "wireless antenna", "rear ports"],
    short: "Block of rear-facing ports for USB, networking, wireless and audio.",
  },
  "cpu-socket": {
    id: "cpu-socket",
    name: "CPU Socket",
    system: "connectivity",
    level: "B",
    tags: ["socket", "lga", "land grid array", "cpu socket", "retention mechanism", "pins"],
    short: "Land-grid-array socket that holds the CPU and its retention mechanism in place.",
    whatItDoes: "Aligns the CPU's contact pads and applies even mounting pressure so every pin makes contact.",
  },

  // ── cpu ───────────────────────────────────────────────────────────────
  cpu: {
    id: "cpu",
    name: "Processor",
    productName: "8-core desktop processor",
    system: "compute",
    level: "A",
    tags: ["cpu", "processor", "chip", "8-core", "stacked cache", "desktop cpu", "cores"],
    short: "Runs game logic, simulation and the instructions that keep everything moving.",
    whatItDoes: "The PC's general-purpose processor. In games it handles simulation, AI, draw-call preparation, physics and operating-system work while feeding the GPU what it needs to build each frame.",
    whyItMatters: "A large stacked cache keeps more of a game's working data close to the cores, which can lift frame rates in cache-sensitive titles without needing a higher clock speed.",
    buying: "Core count and clock speed for the games and background tasks you run, cache size for frame-rate consistency, socket compatibility with your motherboard, and power draw for cooling and power planning.",
    thisBuild: [
      "8 cores / 16 threads",
      "Boost clocks above 5 GHz",
      "A large L3 cache, part of it stacked on the cores",
      "DDR5 and PCIe 5.0",
    ],
    specs: [
      { label: "Cores / threads", value: "8C / 16T" },
      { label: "Boost clock", value: "Above 5 GHz" },
      { label: "L3 cache", value: "Large, partly stacked" },
      { label: "Memory support", value: "DDR5" },
      { label: "PCIe", value: "PCIe 5.0" },
    ],
    brand: {
      eyebrow: "COMPUTE",
      title: "An 8-core desktop processor",
      body: "8 cores, 16 threads, boost clocks above 5 GHz and a large stacked L3 cache.",
    },
    related: ["aio", "dimm-a", "dimm-b", "cpu-socket"],
  },
  "cpu-ihs": {
    id: "cpu-ihs",
    name: "Heat Spreader",
    system: "compute",
    level: "B",
    tags: ["heat spreader", "ihs", "cpu lid", "integrated heat spreader"],
    short: "Metal lid that draws heat off the silicon and gives the cooler a flat contact surface.",
    whatItDoes: "Spreads heat from the die evenly so the cooler's cold plate can remove it efficiently.",
  },
  "cpu-substrate": {
    id: "cpu-substrate",
    name: "Package Substrate",
    system: "compute",
    level: "B",
    tags: ["substrate", "package substrate", "cpu package"],
    short: "Substrate that carries the silicon die and connects it to the socket's pins.",
  },

  // ── memory ────────────────────────────────────────────────────────────
  "dimm-a": {
    id: "dimm-a",
    name: "RAM DIMM 1",
    productName: "32GB DDR5 module",
    system: "memory",
    level: "A",
    tags: ["ram", "memory", "dimm", "ddr5", "32gb", "ddr5-6000", "memory kit", "rgb ram"],
    short: "Fast temporary storage for data the CPU needs right now.",
    whatItDoes: "Sits between long-term storage and active computation, holding loaded assets, world state and working data the CPU needs to reach quickly.",
    whyItMatters: "Faster, higher-capacity memory keeps more of a game's active data ready for the CPU, which helps cache-sensitive workloads like this build's processor.",
    buying: "Capacity for the games and background tasks you run, speed and timings your motherboard and CPU actually support, and a memory overclock profile matched to your platform.",
    thisBuild: [
      "DDR5 memory kit with lit heatspreaders",
      "32GB per module (64GB kit, 2×32GB)",
      "DDR5-6000",
      "CL30",
    ],
    specs: [
      { label: "Capacity", value: "32GB (64GB kit, 2×32GB)" },
      { label: "Speed", value: "DDR5-6000" },
      { label: "CAS latency", value: "CL30" },
    ],
    brand: {
      eyebrow: "MEMORY",
      title: "A 64GB DDR5 kit",
      body: "64GB (2×32GB) of DDR5-6000 CL30 memory with RGB heatspreaders.",
    },
    related: ["dimm-b", "cpu", "dimm-slots"],
  },
  "dimm-a-pcb": {
    id: "dimm-a-pcb",
    name: "DIMM 1 PCB",
    system: "memory",
    level: "B",
    tags: ["ram pcb", "memory pcb", "dimm pcb"],
    short: "Circuit board carrying the memory chips and connecting them to the DIMM slot.",
  },
  "dimm-a-heatspreader-l": {
    id: "dimm-a-heatspreader-l",
    name: "DIMM 1 Heatspreader (Left)",
    system: "memory",
    level: "B",
    tags: ["heatspreader", "ram heatspreader", "memory heatsink"],
    short: "Left-side metal heatspreader helping cool the memory chips beneath it.",
  },
  "dimm-a-heatspreader-r": {
    id: "dimm-a-heatspreader-r",
    name: "DIMM 1 Heatspreader (Right)",
    system: "memory",
    level: "B",
    tags: ["heatspreader", "ram heatspreader", "memory heatsink"],
    short: "Right-side metal heatspreader helping cool the memory chips beneath it.",
  },
  "dimm-a-diffuser": {
    id: "dimm-a-diffuser",
    name: "DIMM 1 RGB Diffuser",
    system: "memory",
    level: "B",
    tags: ["rgb diffuser", "ram rgb", "argb", "light bar"],
    short: "Translucent diffuser that spreads the module's RGB lighting evenly along its top edge.",
  },
  "dimm-b": {
    id: "dimm-b",
    name: "RAM DIMM 2",
    productName: "32GB DDR5 module",
    system: "memory",
    level: "A",
    tags: ["ram", "memory", "dimm", "ddr5", "32gb", "ddr5-6000", "memory kit", "rgb ram"],
    short: "Fast temporary storage for data the CPU needs right now.",
    whatItDoes: "Sits between long-term storage and active computation, holding loaded assets, world state and working data the CPU needs to reach quickly.",
    whyItMatters: "Faster, higher-capacity memory keeps more of a game's active data ready for the CPU, which helps cache-sensitive workloads like this build's processor.",
    buying: "Capacity for the games and background tasks you run, speed and timings your motherboard and CPU actually support, and a memory overclock profile matched to your platform.",
    thisBuild: [
      "DDR5 memory kit with lit heatspreaders",
      "32GB per module (64GB kit, 2×32GB)",
      "DDR5-6000",
      "CL30",
    ],
    specs: [
      { label: "Capacity", value: "32GB (64GB kit, 2×32GB)" },
      { label: "Speed", value: "DDR5-6000" },
      { label: "CAS latency", value: "CL30" },
    ],
    brand: {
      eyebrow: "MEMORY",
      title: "A 64GB DDR5 kit",
      body: "64GB (2×32GB) of DDR5-6000 CL30 memory with RGB heatspreaders.",
    },
    related: ["dimm-a", "cpu", "dimm-slots"],
  },
  "dimm-b-pcb": {
    id: "dimm-b-pcb",
    name: "DIMM 2 PCB",
    system: "memory",
    level: "B",
    tags: ["ram pcb", "memory pcb", "dimm pcb"],
    short: "Circuit board carrying the memory chips and connecting them to the DIMM slot.",
  },
  "dimm-b-heatspreader-l": {
    id: "dimm-b-heatspreader-l",
    name: "DIMM 2 Heatspreader (Left)",
    system: "memory",
    level: "B",
    tags: ["heatspreader", "ram heatspreader", "memory heatsink"],
    short: "Left-side metal heatspreader helping cool the memory chips beneath it.",
  },
  "dimm-b-heatspreader-r": {
    id: "dimm-b-heatspreader-r",
    name: "DIMM 2 Heatspreader (Right)",
    system: "memory",
    level: "B",
    tags: ["heatspreader", "ram heatspreader", "memory heatsink"],
    short: "Right-side metal heatspreader helping cool the memory chips beneath it.",
  },
  "dimm-b-diffuser": {
    id: "dimm-b-diffuser",
    name: "DIMM 2 RGB Diffuser",
    system: "memory",
    level: "B",
    tags: ["rgb diffuser", "ram rgb", "argb", "light bar"],
    short: "Translucent diffuser that spreads the module's RGB lighting evenly along its top edge.",
  },

  // ── storage ───────────────────────────────────────────────────────────
  ssd: {
    id: "ssd",
    name: "NVMe SSD",
    productName: "4TB PCIe 5.0 NVMe SSD",
    system: "storage",
    level: "A",
    tags: ["ssd", "nvme", "storage", "drive", "m.2", "pcie 5.0 ssd", "4tb", "solid state"],
    short: "Stores games and streams data into the system at very high speed.",
    whatItDoes: "Permanent storage that connects over PCI Express, moving large amounts of game data quickly enough to reduce loading delays.",
    whyItMatters: "Faster storage reduces loading delays and supports increasingly aggressive asset streaming, so the game world can arrive as fast as it is requested.",
    buying: "Capacity for your game library, the PCIe generation your motherboard supports, and sustained write speed if you also work with large files or record gameplay.",
    thisBuild: [
      "4TB, M.2 2280",
      "PCIe 5.0 x4, NVMe",
      "Sequential reads well over 10,000 MB/s",
      "TLC NAND",
    ],
    specs: [
      { label: "Capacity", value: "4TB" },
      { label: "Interface", value: "PCIe 5.0 x4" },
      { label: "Protocol", value: "NVMe" },
      { label: "Sequential read", value: "Over 10,000 MB/s class" },
      { label: "Form factor", value: "M.2 2280" },
    ],
    brand: {
      eyebrow: "STORAGE",
      title: "A 4TB PCIe 5.0 drive",
      body: "PCIe 5.0 x4 NVMe storage with sequential reads well past 10,000 MB/s.",
    },
    related: ["motherboard", "m2-heatsink", "chipset-heatsink"],
  },
  "ssd-pcb": {
    id: "ssd-pcb",
    name: "SSD PCB",
    system: "storage",
    level: "B",
    tags: ["ssd pcb", "nvme pcb", "m.2 board"],
    short: "Circuit board carrying the SSD's controller, NAND and connector.",
  },
  "ssd-controller": {
    id: "ssd-controller",
    name: "SSD Controller",
    system: "storage",
    level: "B",
    tags: ["controller", "ssd controller", "nvme controller"],
    short: "Controller chip that manages data flow between the NAND and the PCIe interface.",
    whatItDoes: "Manages the drive's data flow, wear-levelling and error correction between the NAND packages and the PCIe interface.",
  },
  "ssd-nand": {
    id: "ssd-nand",
    name: "NAND Packages",
    system: "storage",
    level: "B",
    tags: ["nand", "flash memory", "3d nand", "tlc nand"],
    short: "NAND flash packages where the drive's data is physically stored.",
    whatItDoes: "Stacked TLC NAND chips that hold the drive's data permanently, even without power.",
  },
  "ssd-label": {
    id: "ssd-label",
    name: "SSD Label",
    system: "storage",
    level: "B",
    tags: ["label", "sticker", "ssd label"],
    short: "Printed label carrying the drive's model, capacity and certification markings.",
  },

  // ── gpu ───────────────────────────────────────────────────────────────
  gpu: {
    id: "gpu",
    name: "Graphics Card",
    productName: "Flagship-class graphics card",
    system: "graphics",
    level: "A",
    tags: ["gpu", "graphics card", "video card", "graphics", "flagship gpu", "gddr7", "quad fan"],
    short: "Turns game data into the frames you see on screen.",
    whatItDoes: "Processes geometry, shaders, lighting, ray tracing and AI-assisted rendering in parallel, with dedicated video memory keeping graphics data close at hand.",
    whyItMatters: "Resolution, visual quality, ray tracing and target frame rate all place substantial load on the graphics processor. It usually has the biggest effect on how a game looks and runs.",
    buying: "GPU generation and memory capacity for the resolution and settings you target, cooler size and case clearance, power connector and PSU headroom, and driver support for the games you play.",
    thisBuild: [
      "Flagship-class graphics processor",
      "Tens of gigabytes of GDDR7",
      "PCIe 5.0",
      "Quad-fan cooler with vapor chamber",
      "About 36 × 15 cm, nearly four slots thick",
    ],
    specs: [
      { label: "Class", value: "Flagship" },
      { label: "Memory", value: "GDDR7" },
      { label: "Shader lanes", value: "Tens of thousands" },
      { label: "Interface", value: "PCIe 5.0" },
      { label: "Cooler", value: "Quad-fan, vapor chamber" },
    ],
    brand: {
      eyebrow: "GRAPHICS",
      title: "A flagship-class graphics card",
      body: "GDDR7 memory, a flagship graphics processor and a four-fan thermal system built around a large heatsink and vapor chamber.",
    },
    related: ["psu", "cable-gpu-16pin", "pcie-slot-1"],
  },
  "gpu-shroud": {
    id: "gpu-shroud",
    name: "GPU Shroud",
    system: "graphics",
    level: "B",
    tags: ["shroud", "gpu shroud", "gpu cover", "graphics card shroud"],
    short: "Outer cover that shapes airflow across the card's heatsink and fans.",
  },
  "gpu-fan-1": {
    id: "gpu-fan-1",
    name: "GPU Fan 1",
    system: "graphics",
    level: "B",
    tags: ["gpu fan", "graphics card fan", "axial fan"],
    short: "First of four fans pulling air down through the GPU's heatsink fins.",
  },
  "gpu-fan-2": {
    id: "gpu-fan-2",
    name: "GPU Fan 2",
    system: "graphics",
    level: "B",
    tags: ["gpu fan", "graphics card fan", "axial fan"],
    short: "Second of four fans pulling air down through the GPU's heatsink fins.",
  },
  "gpu-fan-3": {
    id: "gpu-fan-3",
    name: "GPU Fan 3",
    system: "graphics",
    level: "B",
    tags: ["gpu fan", "graphics card fan", "axial fan"],
    short: "Third of four fans pulling air down through the GPU's heatsink fins.",
  },
  "gpu-fan-4": {
    id: "gpu-fan-4",
    name: "GPU Fan 4",
    system: "graphics",
    level: "B",
    tags: ["gpu fan", "graphics card fan", "axial fan"],
    short: "Fourth of four fans pulling air down through the GPU's heatsink fins.",
  },
  "gpu-backplate": {
    id: "gpu-backplate",
    name: "GPU Backplate",
    system: "graphics",
    level: "B",
    tags: ["backplate", "gpu backplate", "rear plate"],
    short: "Metal plate across the back of the card that adds rigidity and helps with cooling.",
  },
  "gpu-heatsink": {
    id: "gpu-heatsink",
    name: "GPU Heatsink",
    system: "graphics",
    level: "B",
    tags: ["heatsink", "gpu heatsink", "cooling fins"],
    short: "Large finned heatsink that carries heat away from the vapor chamber and heatpipes.",
  },
  "gpu-vapor-chamber": {
    id: "gpu-vapor-chamber",
    name: "Vapor Chamber",
    system: "graphics",
    level: "B",
    tags: ["vapor chamber", "vapour chamber", "heat spreader"],
    short: "Sealed chamber that spreads heat rapidly across the base of the heatsink.",
    whatItDoes: "Uses a phase-change vapour cycle to spread heat far more evenly than solid metal alone, before the heatsink fins carry it away.",
  },
  "gpu-heatpipes": {
    id: "gpu-heatpipes",
    name: "Heatpipes",
    system: "graphics",
    level: "B",
    tags: ["heatpipes", "heat pipes", "copper pipes"],
    short: "Sealed copper pipes that carry heat from the GPU die out across the heatsink.",
    whatItDoes: "Move heat efficiently from the die to the far ends of the heatsink using an internal phase-change cycle.",
  },
  "gpu-pcb": {
    id: "gpu-pcb",
    name: "GPU PCB",
    system: "graphics",
    level: "B",
    tags: ["gpu pcb", "graphics card board", "video card pcb"],
    short: "Circuit board carrying the GPU die, memory and power-delivery components.",
  },
  "gpu-die": {
    id: "gpu-die",
    name: "GPU Die",
    system: "graphics",
    level: "B",
    tags: ["gpu die", "silicon", "gpu chip", "graphics processor"],
    short: "The GPU silicon itself, where geometry, shading and ray tracing are computed.",
    whatItDoes: "Executes the parallel graphics and AI workloads that turn a scene's data into a rendered frame.",
  },
  "gpu-gddr7": {
    id: "gpu-gddr7",
    name: "GDDR7 Memory",
    system: "graphics",
    level: "B",
    tags: ["gddr7", "vram", "graphics memory", "video memory"],
    short: "GDDR7 memory chips that keep textures and render data close to the GPU die.",
    whatItDoes: "High-bandwidth memory dedicated to the GPU, holding textures, render targets and other graphics data it needs immediately.",
  },
  "gpu-vrm": {
    id: "gpu-vrm",
    name: "GPU VRM",
    system: "graphics",
    level: "B",
    tags: ["gpu vrm", "power delivery", "voltage regulator"],
    short: "Voltage-regulation circuitry that supplies clean, stable power to the GPU die.",
    whatItDoes: "Converts and regulates power from the PCIe slot and power cable into the precise voltages the GPU die needs.",
  },
  "gpu-edge-connector": {
    id: "gpu-edge-connector",
    name: "PCIe Edge Connector",
    system: "graphics",
    level: "B",
    tags: ["edge connector", "pcie connector", "gold fingers"],
    short: "Gold-fingered edge connector that plugs the card into the motherboard's PCIe slot.",
  },
  "gpu-power-connector": {
    id: "gpu-power-connector",
    name: "GPU Power Connector",
    system: "graphics",
    level: "B",
    tags: ["16-pin connector", "power connector", "gpu power"],
    short: "16-pin socket on the card where the PSU's dedicated GPU power cable connects.",
  },
  "gpu-bracket": {
    id: "gpu-bracket",
    name: "Rear I/O Bracket",
    system: "graphics",
    level: "B",
    tags: ["bracket", "io bracket", "rear bracket", "display outputs"],
    short: "Steel bracket that bolts the card to the case and carries its display outputs.",
  },

  // ── cpu liquid cooler ─────────────────────────────────────────────────
  aio: {
    id: "aio",
    name: "CPU Liquid Cooler",
    productName: "360 mm all-in-one liquid cooler",
    system: "cooling",
    level: "A",
    tags: ["aio", "cooler", "liquid cooler", "water cooler", "pump", "cpu cooler", "360mm aio", "all-in-one"],
    short: "Moves heat away from the processor and releases it through the radiator.",
    whatItDoes: "The cold plate absorbs heat from the CPU. Coolant carries that heat through the tubes to the radiator, where fans move it into the surrounding air.",
    whyItMatters: "Liquid cooling keeps the CPU running below its thermal limit under sustained gaming and multi-core loads.",
    buying: "Radiator size for your case's mounting points, socket compatibility, pump noise and warranty, and whether the block's screen or lighting matters to you.",
    thisBuild: [
      "360mm radiator, three 120mm fans",
      "Copper cold plate",
      "Full-colour LCD on the pump block",
    ],
    specs: [
      { label: "Radiator size", value: "360mm (about 400 × 120 × 30 mm)" },
      { label: "Fans", value: "3 × 120mm" },
      { label: "Cold plate", value: "Copper" },
      { label: "Display", value: "Full-colour LCD" },
    ],
    brand: {
      eyebrow: "COOLING",
      title: "A 360mm liquid cooler",
      body: "A 360mm radiator, copper cold plate, three 120mm fans and a full-colour LCD cool the processor.",
    },
    related: ["cpu", "aio-radiator", "cpu-socket"],
  },
  "aio-block": {
    id: "aio-block",
    name: "Cooler Block Housing",
    system: "cooling",
    level: "B",
    tags: ["block", "cpu block", "pump block", "cooler head"],
    short: "Housing that sits on the CPU and contains the cold plate, pump and display.",
  },
  "aio-lcd": {
    id: "aio-lcd",
    name: "Cooler LCD",
    system: "cooling",
    level: "B",
    tags: ["lcd", "display", "cooler screen", "aio screen"],
    short: "3.5-inch full-colour display built into the cooler's block.",
  },
  "aio-cold-plate": {
    id: "aio-cold-plate",
    name: "Cold Plate",
    system: "cooling",
    level: "B",
    tags: ["cold plate", "copper plate", "contact plate"],
    short: "Copper plate in direct contact with the CPU's heat spreader.",
    whatItDoes: "Absorbs heat directly from the CPU and transfers it into the coolant flowing above it.",
  },
  "aio-pump": {
    id: "aio-pump",
    name: "Pump",
    system: "cooling",
    level: "B",
    tags: ["pump", "coolant pump", "circulation pump"],
    short: "Pump that circulates coolant between the block and the radiator.",
    whatItDoes: "Drives coolant continuously round the loop so heat picked up at the CPU keeps moving towards the radiator.",
  },
  "aio-tube-a": {
    id: "aio-tube-a",
    name: "Coolant Tube A",
    system: "cooling",
    level: "B",
    tags: ["tube", "coolant tube", "aio hose"],
    short: "Tube carrying heated coolant from the CPU block to the radiator.",
  },
  "aio-tube-b": {
    id: "aio-tube-b",
    name: "Coolant Tube B",
    system: "cooling",
    level: "B",
    tags: ["tube", "coolant tube", "aio hose"],
    short: "Tube returning cooled coolant from the radiator back to the CPU block.",
  },
  "aio-radiator": {
    id: "aio-radiator",
    name: "Radiator",
    system: "cooling",
    level: "A",
    tags: ["radiator", "360mm radiator", "aio radiator", "rad"],
    short: "360mm radiator that sheds the heat the coolant collects from the CPU.",
    whatItDoes: "Coolant flows through the radiator's fin core, where the fans' airflow carries the collected heat out into the case's exhaust.",
    related: ["aio", "aio-fan-1", "aio-fan-2", "aio-fan-3"],
  },
  "aio-radiator-core": {
    id: "aio-radiator-core",
    name: "Radiator Fin Core",
    system: "cooling",
    level: "B",
    tags: ["fin core", "radiator fins", "heat exchanger"],
    short: "Fin stack inside the radiator where heat transfers from the coolant into the airflow.",
  },
  "aio-fan-1": {
    id: "aio-fan-1",
    name: "Radiator Fan 1",
    productName: "120 mm radiator fan",
    system: "cooling",
    level: "A",
    tags: ["fan", "radiator fan", "120mm fan", "120 mm", "aio fan", "argb fan"],
    short: "First of three 120mm fans pulling air through the radiator.",
    whatItDoes: "Pulls air through the radiator fins to carry away the heat the coolant has collected from the CPU.",
    whyItMatters: "Radiator fan speed and airflow directly affect how quickly the liquid loop can shed heat, especially under sustained load.",
    buying: "Static pressure for radiator use, noise level, and ARGB or fan-header compatibility with your motherboard or cooler hub.",
    thisBuild: ["120mm radiator fan", "Ships with the liquid cooler", "ARGB lighting"],
    specs: [
      { label: "Size", value: "120mm" },
      { label: "Included with", value: "The liquid cooler" },
      { label: "Radiator size", value: "360mm (3-fan)" },
    ],
    brand: {
      eyebrow: "COOLING",
      title: "120mm radiator fan",
      body: "One of three 120mm ARGB fans that move air through the 360mm radiator.",
    },
    related: ["aio-fan-2", "aio-fan-3", "aio-radiator"],
  },
  "aio-fan-2": {
    id: "aio-fan-2",
    name: "Radiator Fan 2",
    productName: "120 mm radiator fan",
    system: "cooling",
    level: "A",
    tags: ["fan", "radiator fan", "120mm fan", "120 mm", "aio fan", "argb fan"],
    short: "Second of three 120mm fans pulling air through the radiator.",
    whatItDoes: "Pulls air through the radiator fins to carry away the heat the coolant has collected from the CPU.",
    whyItMatters: "Radiator fan speed and airflow directly affect how quickly the liquid loop can shed heat, especially under sustained load.",
    buying: "Static pressure for radiator use, noise level, and ARGB or fan-header compatibility with your motherboard or cooler hub.",
    thisBuild: ["120mm radiator fan", "Ships with the liquid cooler", "ARGB lighting"],
    specs: [
      { label: "Size", value: "120mm" },
      { label: "Included with", value: "The liquid cooler" },
      { label: "Radiator size", value: "360mm (3-fan)" },
    ],
    brand: {
      eyebrow: "COOLING",
      title: "120mm radiator fan",
      body: "One of three 120mm ARGB fans that move air through the 360mm radiator.",
    },
    related: ["aio-fan-1", "aio-fan-3", "aio-radiator"],
  },
  "aio-fan-3": {
    id: "aio-fan-3",
    name: "Radiator Fan 3",
    productName: "120 mm radiator fan",
    system: "cooling",
    level: "A",
    tags: ["fan", "radiator fan", "120mm fan", "120 mm", "aio fan", "argb fan"],
    short: "Third of three 120mm fans pulling air through the radiator.",
    whatItDoes: "Pulls air through the radiator fins to carry away the heat the coolant has collected from the CPU.",
    whyItMatters: "Radiator fan speed and airflow directly affect how quickly the liquid loop can shed heat, especially under sustained load.",
    buying: "Static pressure for radiator use, noise level, and ARGB or fan-header compatibility with your motherboard or cooler hub.",
    thisBuild: ["120mm radiator fan", "Ships with the liquid cooler", "ARGB lighting"],
    specs: [
      { label: "Size", value: "120mm" },
      { label: "Included with", value: "The liquid cooler" },
      { label: "Radiator size", value: "360mm (3-fan)" },
    ],
    brand: {
      eyebrow: "COOLING",
      title: "120mm radiator fan",
      body: "One of three 120mm ARGB fans that move air through the 360mm radiator.",
    },
    related: ["aio-fan-1", "aio-fan-2", "aio-radiator"],
  },

  // ── power ─────────────────────────────────────────────────────────────
  psu: {
    id: "psu",
    name: "Power Supply",
    productName: "1600 W ATX power supply",
    system: "power",
    level: "A",
    tags: ["psu", "power supply", "1600w", "atx 3.1", "modular psu"],
    short: "Converts mains electricity into regulated power for every component.",
    whatItDoes: "Takes AC power from the wall and supplies the lower-voltage DC rails used by the PC. A high-end GPU can demand substantial power, making stable delivery and correct cabling important.",
    whyItMatters: "A flagship GPU and CPU together can draw significant power under load, and headroom plus a stable, correctly cabled supply protects the rest of the system.",
    buying: "Enough wattage for your GPU and CPU with headroom to spare, an efficiency rating that suits your running costs, native cables for high-power GPU connectors, and a form factor that fits your case.",
    thisBuild: [
      "1600W, top-tier efficiency rating",
      "ATX 3.1",
      "Native 16-pin (12V-2x6) GPU cables",
      "Fully modular",
    ],
    specs: [
      { label: "Wattage", value: "1600W" },
      { label: "Efficiency", value: "Top tier (about 94 % at half load)" },
      { label: "Standard", value: "ATX 3.1" },
      { label: "GPU connectors", value: "16-pin 12V-2x6" },
    ],
    brand: {
      eyebrow: "POWER",
      title: "A 1600W power supply",
      body: "1600W of top-efficiency power with ATX 3.1 support and native 16-pin GPU cables.",
    },
    related: ["gpu", "cable-gpu-16pin", "cable-24pin"],
  },
  "psu-shell": {
    id: "psu-shell",
    name: "PSU Enclosure",
    system: "power",
    level: "B",
    tags: ["psu shell", "psu case", "power supply enclosure"],
    short: "Outer enclosure that houses the PSU's internal power-conversion electronics.",
  },
  "psu-oled": {
    id: "psu-oled",
    name: "PSU OLED Display",
    system: "power",
    level: "B",
    tags: ["oled", "psu display", "power display"],
    short: "Magnetic OLED display on the PSU showing live power draw and status.",
  },
  "psu-fan": {
    id: "psu-fan",
    name: "PSU Fan",
    system: "power",
    level: "B",
    tags: ["psu fan", "power supply fan"],
    short: "Fan that cools the PSU's internal electronics under load.",
  },
  "psu-grille": {
    id: "psu-grille",
    name: "PSU Fan Grille",
    system: "power",
    level: "B",
    tags: ["grille", "fan grille", "vent"],
    short: "Vented grille that lets the PSU's internal fan draw or expel air.",
  },
  "psu-modular-panel": {
    id: "psu-modular-panel",
    name: "Modular Connector Panel",
    system: "power",
    level: "B",
    tags: ["modular panel", "modular connectors", "cable sockets"],
    short: "Panel of modular sockets where only the cables you need are connected.",
  },
  "psu-ac-inlet": {
    id: "psu-ac-inlet",
    name: "AC Inlet",
    system: "power",
    level: "B",
    tags: ["ac inlet", "mains socket", "power cord socket"],
    short: "Socket where the mains power cable connects to the PSU.",
  },
  "psu-internals": {
    id: "psu-internals",
    name: "Power Electronics",
    system: "power",
    level: "B",
    tags: ["power electronics", "psu internals", "rectifier", "transformer"],
    short: "Internal electronics that convert mains AC into the PC's regulated DC rails.",
    whatItDoes: "Converts and regulates incoming mains power into the steady low-voltage DC rails every component depends on.",
  },
  "cable-24pin": {
    id: "cable-24pin",
    name: "24-Pin Motherboard Cable",
    system: "power",
    level: "A",
    tags: ["24-pin cable", "atx cable", "motherboard power cable"],
    short: "Main power cable that feeds the motherboard from the PSU.",
    whatItDoes: "Carries multiple voltage rails from the PSU to the motherboard's 24-pin socket, powering the board and its onboard controllers.",
    related: ["psu", "atx-24pin-socket"],
  },
  "cable-eps-a": {
    id: "cable-eps-a",
    name: "CPU EPS Cable A",
    system: "power",
    level: "A",
    tags: ["eps cable", "cpu power cable", "8-pin cable"],
    short: "8-pin cable that delivers dedicated power from the PSU to the CPU.",
    whatItDoes: "Feeds the motherboard's EPS socket near the CPU socket, supplying the power the processor draws under load.",
    related: ["psu", "eps-sockets", "cpu"],
  },
  "cable-eps-b": {
    id: "cable-eps-b",
    name: "CPU EPS Cable B",
    system: "power",
    level: "A",
    tags: ["eps cable", "cpu power cable", "8-pin cable"],
    short: "Second 8-pin cable providing additional dedicated CPU power from the PSU.",
    whatItDoes: "Feeds the motherboard's second EPS socket, sharing the power load the processor draws under high demand.",
    related: ["psu", "eps-sockets", "cpu"],
  },
  "cable-gpu-16pin": {
    id: "cable-gpu-16pin",
    name: "GPU 16-Pin Power Cable",
    system: "power",
    level: "A",
    tags: ["16-pin cable", "gpu power cable", "gpu 16-pin"],
    short: "Single 16-pin cable that delivers the GPU's full power draw from the PSU.",
    whatItDoes: "Carries the GPU's power directly from the PSU's native 16-pin connector, in place of multiple smaller cables.",
    related: ["psu", "gpu", "gpu-power-connector"],
  },
  "cable-front-io": {
    id: "cable-front-io",
    name: "Front I/O Cable Group",
    system: "power",
    level: "A",
    tags: ["front io cable", "panel cable", "usb cable", "audio cable"],
    short: "Bundle of wires linking the case's front-panel buttons, USB ports and audio jack to the motherboard.",
    whatItDoes: "Connects the power button, reset button, status LEDs, front USB ports and audio jack to their motherboard headers.",
    related: ["motherboard", "front-io"],
  },

  // ── level B added in slice 3 ──────────────────────────────────────────
  "case-tray": {
    id: "case-tray", name: "Motherboard Tray", system: "chassis", level: "B",
    tags: ["tray", "motherboard tray", "backplate", "cable management", "grommets"],
    short: "The steel wall the motherboard mounts to, with grommets for routing cables behind it.",
    whatItDoes: "Carries the motherboard on standoffs and hides the cable runs behind it, so the visible side of the build stays clean and airflow stays clear.",
    related: ["case-frame", "motherboard"],
  },
  "case-rear": {
    id: "case-rear", name: "Rear Panel", system: "chassis", level: "B",
    tags: ["rear", "back panel", "exhaust", "slot covers", "io cutout"],
    short: "Rear steel panel with the exhaust fan opening, the I/O cut-out and the expansion-slot covers.",
    whatItDoes: "Everything that leaves the machine passes through here: exhaust air, the motherboard's ports, the graphics card's display outputs and the mains lead.",
    related: ["case-frame", "fan-rear", "rear-io", "gpu-bracket"],
  },
  "case-floor": {
    id: "case-floor", name: "Base Plate", system: "chassis", level: "B",
    tags: ["floor", "base", "bottom", "psu mount", "dust filter"],
    short: "Floor of the chassis. The power supply sits on it and its intake breathes through it.",
    whatItDoes: "Mounts the PSU and carries the bottom dust filter that the supply's fan draws through.",
    related: ["case-frame", "psu", "case-feet"],
  },
  "case-top-frame": {
    id: "case-top-frame", name: "Top Frame", system: "chassis", level: "B",
    tags: ["top", "roof", "radiator mount", "vent"],
    short: "Vented top frame the radiator hangs from, under the removable top panel.",
    whatItDoes: "Takes the weight of a 360 or 420 mm radiator and its fans and lets their exhaust leave through the top panel's mesh.",
    related: ["case-frame", "panel-top", "aio-radiator"],
  },
  "fan-front-1-rotor": rotorOf("fan-front-1-rotor", "Front Fan 1", "fan-front-1", "cooling", "pulling cool air in through the front mesh"),
  "fan-front-2-rotor": rotorOf("fan-front-2-rotor", "Front Fan 2", "fan-front-2", "cooling", "pulling cool air in through the front mesh"),
  "fan-front-3-rotor": rotorOf("fan-front-3-rotor", "Front Fan 3", "fan-front-3", "cooling", "pulling cool air in through the front mesh"),
  "fan-rear-rotor": rotorOf("fan-rear-rotor", "Rear Fan", "fan-rear", "cooling", "pushing warm air out of the back of the case"),
  "aio-fan-1-rotor": rotorOf("aio-fan-1-rotor", "Radiator Fan 1", "aio-fan-1", "cooling", "forcing air through the radiator's fins"),
  "aio-fan-2-rotor": rotorOf("aio-fan-2-rotor", "Radiator Fan 2", "aio-fan-2", "cooling", "forcing air through the radiator's fins"),
  "aio-fan-3-rotor": rotorOf("aio-fan-3-rotor", "Radiator Fan 3", "aio-fan-3", "cooling", "forcing air through the radiator's fins"),
  "gpu-fan-1-rotor": rotorOf("gpu-fan-1-rotor", "GPU Fan 1", "gpu-fan-1", "graphics", "driving air through the card's heatsink"),
  "gpu-fan-2-rotor": rotorOf("gpu-fan-2-rotor", "GPU Fan 2", "gpu-fan-2", "graphics", "driving air through the card's heatsink"),
  "gpu-fan-3-rotor": rotorOf("gpu-fan-3-rotor", "GPU Fan 3", "gpu-fan-3", "graphics", "driving air through the card's heatsink"),
  "gpu-fan-4-rotor": rotorOf("gpu-fan-4-rotor", "GPU Fan 4", "gpu-fan-4", "graphics", "pulling air straight through the open end of the heatsink"),
  "psu-fan-rotor": rotorOf("psu-fan-rotor", "PSU Fan", "psu-fan", "power", "cooling the power electronics inside the supply"),
  "dimm-a-chips": {
    id: "dimm-a-chips", name: "DIMM A Memory Packages", system: "memory", level: "B",
    tags: ["dram", "memory chips", "packages", "ics", "pmic"],
    short: "The DRAM packages on both faces of the module, plus the power-management chip, under the heatspreaders.",
    whatItDoes: "Each package holds the memory cells themselves. DDR5 also moves power regulation onto the module, which is the small chip near the top edge.",
    related: ["dimm-a", "dimm-a-heatspreader-l", "dimm-a-heatspreader-r"],
  },
  "dimm-b-chips": {
    id: "dimm-b-chips", name: "DIMM B Memory Packages", system: "memory", level: "B",
    tags: ["dram", "memory chips", "packages", "ics", "pmic"],
    short: "The DRAM packages on both faces of the module, plus the power-management chip, under the heatspreaders.",
    whatItDoes: "Each package holds the memory cells themselves. DDR5 also moves power regulation onto the module, which is the small chip near the top edge.",
    related: ["dimm-b", "dimm-b-heatspreader-l", "dimm-b-heatspreader-r"],
  },
  "cpu-dies": {
    id: "cpu-dies", name: "CPU Dies", system: "compute", level: "B",
    tags: ["die", "chiplet", "core die", "io die", "stacked cache", "silicon"],
    short: "Under the heat spreader: two core chiplets, the I/O die and the stacked cache.",
    whatItDoes: "The cores live on the compute chiplets, the memory controller and PCIe lanes on the I/O die, and the extra cache sits stacked on a compute die so it stays physically close to the cores.",
    related: ["cpu", "cpu-ihs", "cpu-substrate"],
  },
} satisfies Record<PartId, PartContent>;

// ── scroll story: 17 chapters, story + brand copy per beat ─────────────────

export const CHAPTERS: Chapter[] = [
  {
    id: "arrival",
    from: 0,
    to: 0.04,
    world: "cpu-micro",
    story: {
      eyebrow: "THE BUILD",
      title: "Every frame starts somewhere.",
      body: "Follow the work through a flagship gaming PC, then pull the whole machine apart.",
    },
    brand: {
      eyebrow: "THE BUILD",
      title: "Performance is a system.",
      body: "Go inside a flagship gaming PC.",
    },
  },
  {
    id: "cpu",
    from: 0.04,
    to: 0.12,
    world: "cpu-micro",
    story: {
      eyebrow: "COMPUTE",
      title: "A frame begins here.",
      body: "The CPU runs the game world behind the image: simulation, logic, AI, operating-system work and preparation for the next frame.",
    },
    brand: {
      eyebrow: "COMPUTE",
      title: "Eight cores, sixteen threads",
      body: "Eight cores, sixteen threads and a stacked L3 cache form the compute heart of this build.",
    },
  },
  {
    id: "cache",
    from: 0.12,
    to: 0.18,
    world: "cpu-micro",
    story: {
      eyebrow: "COMPUTE",
      title: "Keep the important data close.",
      body: "Games repeatedly revisit large working sets of information. Fast cache reduces how often the processor waits for data farther away.",
    },
    brand: {
      eyebrow: "COMPUTE",
      title: "Stacked cache",
      body: "A large cache layer keeps more frequently accessed data close to the processor cores.",
    },
  },
  {
    id: "package",
    from: 0.18,
    to: 0.24,
    world: "machine",
    story: {
      eyebrow: "COMPUTE",
      title: "One processor. Millions of operations.",
      body: "The pathways you just flew through were inside this one chip, now locked into its socket.",
    },
    brand: {
      eyebrow: "COMPUTE",
      title: "One processor",
      body: "Socketed and ready: 8 cores and 16 threads in a single package.",
    },
  },
  {
    id: "memory",
    from: 0.24,
    to: 0.31,
    world: "machine",
    story: {
      eyebrow: "MEMORY",
      title: "The working set.",
      body: "RAM holds active game data close enough for the processor to reach quickly.",
    },
    brand: {
      eyebrow: "MEMORY",
      title: "64GB DDR5-6000",
      body: "Two 32GB DDR5 modules provide the system memory for this build.",
    },
  },
  {
    id: "motherboard",
    from: 0.31,
    to: 0.39,
    world: "machine",
    story: {
      eyebrow: "CONNECTIVITY",
      title: "Everything meets here.",
      body: "The motherboard provides the physical connections, controllers, data lanes and power paths that let the components operate as one system.",
    },
    brand: {
      eyebrow: "CONNECTIVITY",
      title: "An E-ATX motherboard",
      body: "PCIe 5.0, DDR5, five M.2 positions, USB4 and high-end platform connectivity.",
    },
  },
  {
    id: "storage",
    from: 0.39,
    to: 0.45,
    world: "machine",
    story: {
      eyebrow: "STORAGE",
      title: "The world has to arrive first.",
      body: "Games live on storage until their assets are requested. Modern PCIe NVMe drives can move enormous amounts of data into the system.",
    },
    brand: {
      eyebrow: "STORAGE",
      title: "4TB of PCIe 5.0 storage",
      body: "PCIe 5.0 x4 NVMe storage with sequential reads well past 10,000 MB/s.",
    },
  },
  {
    id: "pcie",
    from: 0.45,
    to: 0.49,
    world: "machine",
    story: {
      eyebrow: "CONNECTIVITY",
      title: "The high-speed link.",
      body: "PCI Express connects the graphics card directly into the platform.",
    },
    brand: {
      eyebrow: "CONNECTIVITY",
      title: "PCIe 5.0",
      body: "Two physical PCIe 5.0 x16 slots connect the platform's fastest devices directly to the CPU and chipset.",
    },
  },
  {
    id: "gpu",
    from: 0.49,
    to: 0.59,
    world: "gpu-micro",
    story: {
      eyebrow: "GRAPHICS",
      title: "Now build the frame.",
      body: "The GPU performs huge amounts of graphics work in parallel: geometry, materials, lighting, ray tracing and more.",
    },
    brand: {
      eyebrow: "GRAPHICS",
      title: "A flagship-class GPU",
      body: "GDDR7 memory and a flagship graphics processor built for high-end gaming.",
    },
  },
  {
    id: "vram",
    from: 0.59,
    to: 0.64,
    world: "gpu-micro",
    story: {
      eyebrow: "GRAPHICS",
      title: "Graphics memory, beside the GPU.",
      body: "Textures, render targets, geometry and other graphics data stay in dedicated high-bandwidth memory.",
    },
    brand: {
      eyebrow: "GRAPHICS",
      title: "GDDR7 memory",
      body: "Dedicated graphics memory keeps large gaming workloads close to the GPU.",
    },
  },
  {
    id: "gpu-thermal",
    from: 0.64,
    to: 0.69,
    world: "machine",
    story: {
      eyebrow: "COOLING",
      title: "Performance becomes heat.",
      body: "The cooling system has to move heat away from the GPU quickly enough to keep it within its thermal limits.",
    },
    brand: {
      eyebrow: "COOLING",
      title: "Four-fan cooling",
      body: "A large heatsink, vapor chamber and four-fan layout move heat away from the GPU.",
    },
  },
  {
    id: "cpu-cooling",
    from: 0.69,
    to: 0.75,
    world: "machine",
    story: {
      eyebrow: "COOLING",
      title: "Move the heat.",
      body: "The cold plate absorbs CPU heat. Coolant carries it to the radiator, where fans move it into the surrounding air.",
    },
    brand: {
      eyebrow: "COOLING",
      title: "A 360mm liquid cooler",
      body: "A 360mm radiator, pump and block assembly and three 120mm fans cool the processor.",
    },
  },
  {
    id: "power",
    from: 0.75,
    to: 0.81,
    world: "machine",
    story: {
      eyebrow: "POWER",
      title: "Nothing moves without power.",
      body: "The PSU converts mains electricity into regulated power for the components throughout the PC.",
    },
    brand: {
      eyebrow: "POWER",
      title: "1600W, top-tier efficiency",
      body: "ATX 3.1, 1600W output and native high-power GPU connectivity for this flagship build.",
    },
  },
  {
    id: "airflow",
    from: 0.81,
    to: 0.86,
    world: "machine",
    story: {
      eyebrow: "COOLING",
      title: "Cooling is not one component.",
      body: "The entire chassis manages where cool air enters, where heat builds and where warm air leaves.",
    },
    brand: {
      eyebrow: "COOLING",
      title: "Front to back",
      body: "Three 140mm front intake fans and one 140mm rear exhaust fan move air through the case.",
    },
  },
  {
    id: "internal-reveal",
    from: 0.86,
    to: 0.90,
    world: "machine",
    story: {
      eyebrow: "THE BUILD",
      title: "One system.",
      body: "Processor, memory, graphics, storage, cooling and power: individually components, together the machine running the game.",
    },
    brand: {
      eyebrow: "THE BUILD",
      title: "Built to work together.",
      body: "A complete flagship gaming system, revealed from the inside out.",
    },
  },
  {
    id: "exterior-reveal",
    from: 0.90,
    to: 0.94,
    world: "machine",
    story: {
      eyebrow: "THE BUILD",
      title: "The complete build.",
      body: "Every internal system now sits inside the finished full-tower case.",
    },
    brand: {
      eyebrow: "THE BUILD",
      title: "The full tower",
      body: "A large tempered-glass tower built to show off everything inside it.",
    },
  },
  {
    id: "explode",
    from: 0.94,
    to: 1.0,
    world: "machine",
    story: {
      eyebrow: "THE BUILD",
      title: "Now pull it apart.",
      body: "Every major part of the machine is now yours to inspect.",
    },
    brand: {
      eyebrow: "THE BUILD",
      title: "Explore every component.",
      body: "Select a product, isolate it and go deeper.",
    },
  },
];

// ── hero ────────────────────────────────────────────────────────────────

export const HERO: { story: CopyBlock; brand: CopyBlock } = {
  story: {
    eyebrow: "JARVISING · ENTRY 003",
    title: "Every frame starts somewhere.",
    body: "Follow data through a flagship gaming PC, from processor and memory to graphics, cooling and power, then pull the entire machine apart.",
  },
  brand: {
    eyebrow: "JARVISING · ENTRY 003",
    title: "Performance is a system.",
    body: "See how every component works together, then inspect every piece individually.",
  },
};

// ── source & credits ───────────────────────────────────────────────────

export const CREDITS: string[] = [
  "Internal data-flow visualisations are illustrative. The physical parts are modelled at the published dimensions of a real flagship build, then drawn as generic parts.",
  "No brands, on purpose: no manufacturer, product-line or model names, and no logos, marks or trade dress are reproduced. Specifications are given as generic classes rather than one product's exact numbers.",
  "Specifications checked 7 September 2026, and generalised for this page.",
  "Made for jarvising.com with three.js. Source: github.com/StovBuilds/jarvising (MIT).",
];
