// The registry of inspectable node ids. content.ts must describe every id
// here; the builders must create a PartNode for every id here. A typo on
// either side is a type error, not a silent hole in the atlas.

export const PART_IDS = [
  // ── chassis ───────────────────────────────────────────────────────────
  "case-frame",
  "glass-left",
  "panel-right",
  "panel-front",
  "panel-top",
  "psu-shroud",
  "front-io",
  "case-feet",
  // ── case cooling ──────────────────────────────────────────────────────
  "fan-front-1",
  "fan-front-2",
  "fan-front-3",
  "fan-rear",
  // ── motherboard ───────────────────────────────────────────────────────
  "motherboard",
  "vrm-heatsink-top",
  "vrm-heatsink-side",
  "io-shroud",
  "chipset-heatsink",
  "m2-heatsink",
  "pcie-slot-1",
  "pcie-slot-2",
  "dimm-slots",
  "atx-24pin-socket",
  "eps-sockets",
  "rear-io",
  "cpu-socket",
  // ── cpu ───────────────────────────────────────────────────────────────
  "cpu",
  "cpu-ihs",
  "cpu-substrate",
  // ── memory ────────────────────────────────────────────────────────────
  "dimm-a",
  "dimm-a-pcb",
  "dimm-a-heatspreader-l",
  "dimm-a-heatspreader-r",
  "dimm-a-diffuser",
  "dimm-b",
  "dimm-b-pcb",
  "dimm-b-heatspreader-l",
  "dimm-b-heatspreader-r",
  "dimm-b-diffuser",
  // ── storage ───────────────────────────────────────────────────────────
  "ssd",
  "ssd-pcb",
  "ssd-controller",
  "ssd-nand",
  "ssd-label",
  // ── gpu ───────────────────────────────────────────────────────────────
  "gpu",
  "gpu-shroud",
  "gpu-fan-1",
  "gpu-fan-2",
  "gpu-fan-3",
  "gpu-fan-4",
  "gpu-backplate",
  "gpu-heatsink",
  "gpu-vapor-chamber",
  "gpu-heatpipes",
  "gpu-pcb",
  "gpu-die",
  "gpu-gddr7",
  "gpu-vrm",
  "gpu-edge-connector",
  "gpu-power-connector",
  "gpu-bracket",
  // ── cpu liquid cooler ─────────────────────────────────────────────────
  "aio",
  "aio-block",
  "aio-lcd",
  "aio-cold-plate",
  "aio-pump",
  "aio-tube-a",
  "aio-tube-b",
  "aio-radiator",
  "aio-radiator-core",
  "aio-fan-1",
  "aio-fan-2",
  "aio-fan-3",
  // ── power ─────────────────────────────────────────────────────────────
  "psu",
  "psu-shell",
  "psu-oled",
  "psu-fan",
  "psu-grille",
  "psu-modular-panel",
  "psu-ac-inlet",
  "psu-internals",
  "cable-24pin",
  "cable-eps-a",
  "cable-eps-b",
  "cable-gpu-16pin",
  "cable-front-io",
  // ── level B added in slice 3 ──────────────────────────────────────────
  "case-tray",
  "case-rear",
  "case-floor",
  "case-top-frame",
  "fan-front-1-rotor",
  "fan-front-2-rotor",
  "fan-front-3-rotor",
  "fan-rear-rotor",
  "aio-fan-1-rotor",
  "aio-fan-2-rotor",
  "aio-fan-3-rotor",
  "gpu-fan-1-rotor",
  "gpu-fan-2-rotor",
  "gpu-fan-3-rotor",
  "gpu-fan-4-rotor",
  "psu-fan-rotor",
  "dimm-a-chips",
  "dimm-b-chips",
  "cpu-dies",
] as const;

export type PartId = (typeof PART_IDS)[number];
